//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTwitter.Web.Commanding {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommandBase", Namespace="http://schemas.datacontract.org/2004/07/Ncqrs.Commanding")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SimpleTwitter.Web.Commanding.PostNewTweetCommand))]
    public partial class CommandBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid CommandIdentifierk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CommandIdentifier>k__BackingField", IsRequired=true)]
        public System.Guid CommandIdentifierk__BackingField {
            get {
                return this.CommandIdentifierk__BackingFieldField;
            }
            set {
                if ((this.CommandIdentifierk__BackingFieldField.Equals(value) != true)) {
                    this.CommandIdentifierk__BackingFieldField = value;
                    this.RaisePropertyChanged("CommandIdentifierk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostNewTweetCommand", Namespace="http://schemas.datacontract.org/2004/07/SimpleTwitter.Commands")]
    [System.SerializableAttribute()]
    public partial class PostNewTweetCommand : SimpleTwitter.Web.Commanding.CommandBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WhoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Who {
            get {
                return this.WhoField;
            }
            set {
                if ((object.ReferenceEquals(this.WhoField, value) != true)) {
                    this.WhoField = value;
                    this.RaisePropertyChanged("Who");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Commanding.ISimpleTwitterCommandService")]
    public interface ISimpleTwitterCommandService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleTwitterCommandService/Excecute", ReplyAction="http://tempuri.org/ISimpleTwitterCommandService/ExcecuteResponse")]
        void Excecute(SimpleTwitter.Web.Commanding.PostNewTweetCommand command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleTwitterCommandServiceChannel : SimpleTwitter.Web.Commanding.ISimpleTwitterCommandService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleTwitterCommandServiceClient : System.ServiceModel.ClientBase<SimpleTwitter.Web.Commanding.ISimpleTwitterCommandService>, SimpleTwitter.Web.Commanding.ISimpleTwitterCommandService {
        
        public SimpleTwitterCommandServiceClient() {
        }
        
        public SimpleTwitterCommandServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleTwitterCommandServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleTwitterCommandServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleTwitterCommandServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Excecute(SimpleTwitter.Web.Commanding.PostNewTweetCommand command) {
            base.Channel.Excecute(command);
        }
    }
}
